# Generated by Django 5.1.3 on 2024-11-30 11:41

import django.db.models.deletion
import filebrowser.fields
import lite_cms_page.fields
import mptt.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Is generated if no value has been specified', max_length=200, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expiry_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown after this time", null=True, verbose_name='Expires on')),
                ('slug', models.SlugField(blank=True, help_text='Is generated if no value has been specified', max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
                ('name', models.CharField(blank=True, help_text='Name of menu item.', max_length=50, verbose_name='name')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('url', lite_cms_page.fields.URLOrRelativeURLField(blank=True, null=True, verbose_name='URL')),
                ('ext', models.BooleanField(default=False, verbose_name='Open in new window')),
                ('static', models.BooleanField(default=False, help_text='Element ist for navigation only, no link if selected.', verbose_name='Static Element')),
                ('nav_img', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='menu image')),
                ('template', models.CharField(blank=True, max_length=50, null=True, verbose_name='Template')),
                ('login_required', models.BooleanField(default=False, help_text='If checked, only logged in users can view this page', verbose_name='Login required')),
                ('breadcrumb_exclude', models.BooleanField(default=False, help_text='Will be excluded from Breadcumbs, if checked', verbose_name='Exclude from Breadcrumbs')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menus', models.ManyToManyField(blank=True, to='lite_cms_page.menu', verbose_name='Menus')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lite_cms_page.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['tree_id', 'lft'],
            },
        ),
    ]
